<?php
  $lang['number']		= 'Numer faktury';
  $lang['date'] 		= 'Data wystawienia';
  $lang['time']			= 'Termin platnosci';
  $lang['due'] 			= 'Termin platnosci';
  $lang['to'] 			= 'Nabywca';
  $lang['from'] 		= 'Sprzedawca';
  $lang['product'] 		= 'Produkt';
  $lang['qty'] 			= 'Ilosc';
  $lang['price'] 		= 'Cena';
  $lang['discount'] 	= 'Rabat';
  $lang['vat'] 			= 'Vat';
  $lang['total'] 		= 'Razem';
  $lang['page'] 		= 'Strona';
  $lang['page_of'] 		= 'z';
?>